<?php echo $this->doctype() . "\n"; ?>
<?php echo $this->html5BoilerplateHtml($this->lang, false); ?>
<head>
<?php echo $this->headMeta() . "\n"; ?>
<?php echo $this->headTitle() . "\n"; ?>
<?php echo $this->headScript() . "\n"; ?>
<script src="<?php echo $this->baseUrl("js/libs/modernizr-1.6.min.js"); ?>"></script>
<script src="<?php echo $this->baseUrl("js/libs/jquery.jplayer.min.js"); ?>"></script>
<script src="<?php echo $this->baseUrl("js/libs/jquery-ui-1.8.9.min.js"); ?>"></script>
<script src="<?php echo $this->baseUrl("js/libs/jquery-validate-1.5.1.min.js"); ?>"></script>
<script src="<?php echo $this->baseUrl("js/libs/jquery.qtip-1.0.0-rc3.min.js"); ?>"></script>
<!--<script src="<?php echo $this->baseUrl("webforms2/webforms2-p.js"); ?>"></script>-->
<link rel="stylesheet" href="<?php echo $this->baseUrl("ui-themes/base/jquery.ui.all.css"); ?>">

<link rel="stylesheet" href="<?php echo $this->baseUrl("components/spinner/ui.spinner.css"); ?>">
<script src="<?php echo $this->baseUrl("components/spinner/ui.spinner.js"); ?>"></script>

<script src="<?php echo $this->baseUrl("components/placeholder/jquery.placehold-0.2.min.js"); ?>"></script>
<script src="<?php echo $this->baseUrl("js/html5forms.fallback.js"); ?>"></script>

<link rel="stylesheet" href="<?php echo $this->baseUrl("css/slide.css"); ?>">
<script src="<?php echo $this->baseUrl("js/slide.js"); ?>"></script>
<script src="http://connect.facebook.net/en_US/all.js"></script>

<?php echo $this->headLink() . "\n"; ?>

<?php echo $this->inlineScript()->setScript(sprintf("var baseUrl = '%s';", $this->baseUrl(''))); ?>

<script>
</script>
</head>
<body>
<div id="fb-root"></div>
<div id="bodyShadow">
<!-- Panel -->
<div id="toppanel">
    <div id="panel" class="panel">
		<div class="content clearfix">
			<div class="left">
    		
        	<div class="tab2_container">
                <div id="tab2_1" class="tab2_content">
                    <h1>Welcome to ñandú!</h1>
                    <h2>Explanation</h2>
                    <p class="grey">
                    Since the natural environment for music are our brains, you are the environment and the natural selector in this case.</p>
                    <!--<p class="grey">Feel free to do anything you wish. The only limit is your imagination! :-)</p>-->
                    <?php if ($this->evolving === true) { ?>
                    <h2>Download the MIDI files</h2>
                    <p class="grey">Genotype <a href="<?php echo $this->baseUrl('/audio/'.$this->melodyAfilename.'.mid'); ?>" title="Download">A &raquo;</a> | Genotype <a href="<?php echo $this->baseUrl('/audio/'.$this->melodyBfilename.'.mid'); ?>" title="Download">B &raquo;</a></p>
                    <?php } ?>
                </div>
                <div id="tab2_2" class="tab2_content">
                    <h1>How to use</h1>
                    
                    <p class="grey">When you are in the <i>evolve</i> mode you are faced with two blobs of genetic material. 
                    Pick one that you like best. 
                    The one you have chosen will become a parent for a new iteration and will also survive to the next generation in an unchanged form as <i>'Genotype A'</i> (the one on the left).
                    <br/>This way, you can keep clicking on <i>'Genotype A'</i> until the other one sounds better to you. <br />You may stop this process at any time.</p>
                </div>
            </div>
            
                
                <ul class="tabs2">
                    <li><a href="#tab2_1" class="tablink">Welcome</a></li>
                    <li><a href="#tab2_2" class="tablink">How to</a></li>
                </ul>
			</div>
    		
			<div class="left right">

                <div class="tab_container">
                    <div id="tab1" class="tab_content">
                        <h1>Change species to evolve</h1>
                        <form action="#" class="" method="post" id="speciesPicker">
                        <label id="speciesPickerLabel" for="speciesPickerSelect">
                            <h2>Select species</2>
                        </label>
                        <div class="row selectSpecies">
                            <select class="field dropdown" id="speciesPickerSelect" name="speciesId">
                        <?php foreach ($this->allSpecies as $species):?>
                                <option <?php echo $this->species->id === $species->id ? 'selected="selected"' : '';?> value="<?php echo $species->id?>"> <?php echo $species->id.': '.$species->name?> </option>
                        <?php endforeach; ?>
                        <?php if ($this->evolving === false) echo '<option selected="selected" value=""> </option>'; ?>
                            </select>
                        </div>
                        </form>
                    </div>
                    <div id="tab2" class="tab_content">
                        <h1>Create your own species</h1>
                        <form action="<?php echo $this->url(array(), 'index', true); ?>" method="post" id="createSpecies">
                            <div class="row" id="nameofspecieslabel">
                                <label class="grey" for="txt_Nameofspecies" id="Nameofspecies-ariaLabel">Name of species:</label>
                                <input class="field" id="txt_Nameofspecies" name="name" type="text" aria-labelledby="Nameofspecies-ariaLabel" required autofocus minlength="4" /> <!-- Try to only use numbers and letters pattern="^([a-z0-9ąęśćółżź~@#!\(\)\s]*)$" required autofocus minlength="4" -->
                            </div>
                            <div class="row" id="scalelabel">
                                <label class="grey" for="sel_Scale" id="Scale-ariaLabel">Scale:</label>
                                <select class="field" id="sel_Scale" name="scale_type" aria-labelledby="Scale-ariaLabel" disabled="true">
                            		<option selected="selected" value="0">Major (dur)</option>
                            		<option value="1">Minor (moll)</option>
                            		<option value="2">Minor harmonic</option>
                            	</select>
                            </div>
                            <div class="row" id="tempolabel">
                            	<label class="grey" for="sldr_TempoBPM" id="TempoBPM-ariaLabel">Tempo BPM:</label>
                            	<input class="field required" type="number" id="sldr_TempoBPM" name="tempo" aria-labelledby="TempoBPM-ariaLabel" min="20" max="250" step="1" value="97" disabled="true" /> <!--  -->
                            </div>
                        	<div class="row" id="instrumentlabel">
                        		<label class="grey" for="sel_Instrument" id="Instrument-ariaLabel">Instrument:</label>
                        		<select class="field" id="sel_Instrument" name="instrument" aria-labelledby="Instrument-ariaLabel" disabled="true">
                        			<option value="0">Piano</option>
                        			<option selected="selected" value="12">Vibes</option>
                        			<option value="16">Organ</option>
                        		</select>
                        	</div>
                        	<div class="row" id="referencelabel">
                        		<label class="grey" for="Referencenote" id="Referencenote-ariaLabel">Reference note:</label>
                        		<input class="field required" id="Referencenote" name="reference_note" type="number" aria-labelledby="Referencenote-ariaLabel" min="20" max="200" step="1" value="60" disabled="true" />
                        	</div>
                        	<div class="row">
                        	<input type="submit" value="Create species" />
                        	</div>
                        </form>
                    </div>
                </div>
                
                <ul class="tabs">
                    <li><a href="#tab1" class="tablink">Select</a></li>
                    <li><a href="#tab2" class="tablink">Create</a></li>
                </ul>

    		    
			</div>
		</div>
</div>	

<!-- The tab on top -->	
<div class="tab">
	<ul class="login">
		<li class="left">&nbsp;</li>
		<li><strong>
    	<?php if ($this->evolving === false) echo '[please select species]'; 
    	    else echo $this->species->name; ?></strong></li>
		<li class="sep">|</li>
		<li id="toggle">
			<a id="open" class="open" href="#">Select | Create</a>
			<a id="close" style="display: none;" class="close" href="#">Close Panel</a>			
		</li>
		<li class="right">&nbsp;</li>
	</ul> 
</div> <!-- / top -->
	
</div> <!--panel -->

<div id="dialog-overlay"></div>
<div id="dialog-box">
    <div class="dialog-content">
        <div id="dialog-message"></div>
    </div>
</div>

<div id="wrapper">
    <section id="header">
        <header>
        <h1><a href="<?php echo $this->baseUrl('/'); ?>">ñandú</a><small>Genetic Music Evolution</small></h1>
        </header>
    </section>
	<section id="content">
        <article>
        <?php echo $this->layout()->content . "\n" ?>
        </article>
    </section>
</div>

<?php echo $this->partial('footer-layout.phtml') . "\n"; ?>
<?php //echo $this->headScript() . "\n"; ?>
<?php //echo $this->partial('footer.phtml') . "\n"; ?>
</div>
</body>
</html>