<?php echo $this->doctype() . "\n"; ?>
<?php echo $this->html5BoilerplateHtml($this->lang, false); ?>
<head>
<?php echo $this->headMeta() . "\n"; ?>
<?php echo $this->headTitle() . "\n"; ?>
<?php echo $this->headLink() . "\n"; ?>
<?php echo $this->headScript() . "\n"; ?>
<script src="<?php echo $this->baseUrl("js/libs/modernizr-1.6.min.js"); ?>"></script>
<script src="<?php echo $this->baseUrl("js/libs/jquery.jplayer.min.js"); ?>"></script>
<script src="<?php echo $this->baseUrl("webforms2/webforms2-p.js"); ?>"></script>
<script src="<?php echo $this->baseUrl("js/jquery-ui-1.8.9.min.js"); ?>"></script>

<link rel="stylesheet" href="<?php echo $this->baseUrl("components/spinner/ui.spinner.css"); ?>">
<script src="<?php echo $this->baseUrl("components/spinner/ui.spinner.js"); ?>"></script>
<link rel="stylesheet" href="<?php echo $this->baseUrl("components/colorpicker/colorpicker.css"); ?>">
<script src="<?php echo $this->baseUrl("components/colorpicker/colorpicker.js"); ?>"></script>

<script src="<?php echo $this->baseUrl("components/placeholder/jquery.placehold-0.2.min.js"); ?>"></script>


<?php echo $this->inlineScript()->setScript(sprintf("var baseUrl = '%s';", $this->baseUrl(''))); ?>

</head>
<body>

<div id="wrapper">
    <section id="header">
        <header>
        <h1>Ñandú<small>Genetic Music Evolution</small></h1>
        </header>
    </section>
	<section id="content">
        <article>
        <?php echo $this->layout()->content . "\n" ?>
        </article>
    </section>
</div>

<?php //echo $this->partial('footer-layout.phtml') . "\n"; ?>
<?php //echo $this->headScript() . "\n"; ?>
<?php //echo $this->partial('footer.phtml') . "\n"; ?>
</body>
</html>