<header>
<h2>Pomyślna rejestracja konta</h2>
</header>
<p>Twoje konto zostało poprawnie zarejestrowane, jednakże aby móc skorzystać z serwisu, musisz najpierw je aktywować.</p>
<p>W tym celu na Twój adres <b><?php echo $this->user['email']?></b> wysłana została wiadomość z linkiem do strony aktywacyjnej.</p>
<footer>
<p>Możesz już wrócić do <a href="<?php echo $this->url(array(), 'index'); ?>">strony głównej</a>.</p>
</footer>