<form method="<?php echo $this->element->getMethod(); ?>" action="<?php echo $this->element->getAction(); ?>">
<fieldset>
	<?php if (count($this->element->getErrorMessages())): ?>
	<p class="error"><?php echo ltrim(implode('. ', $this->element->getErrorMessages()) . '.', '.'); ?></p>
	<?php endif; ?>
	<p>
		<label for="email">E-mail:</label>
		<input type="email" id="email" name="<?php echo $this->element->email->getName(); ?>" value="<?php echo $this->element->email->getValue(); ?>" maxlength="128" required="required">
		<?php if (count($this->element->email->getMessages()) > 0): ?>
		<span class="error"><?php echo ltrim(implode('. ', $this->element->email->getMessages()) . '.', '.'); ?></span>
		<?php endif; ?>
	</p>
	<p>
		<label for="password">Hasło:</label>
		<input type="password" id="password" name="<?php echo $this->element->password->getName(); ?>" required="required">
		<?php if (count($this->element->password->getMessages()) > 0): ?>
		<span class="error"><?php echo ltrim(implode('. ', $this->element->password->getMessages()) . '.', '.'); ?></span>
		<?php endif; ?>
	</p>
	<p>
		<button class="button" type="submit">Zaloguj się</button>
	</p>
</fieldset>
</form>
