Cześć, <?php echo $this->nickname; ?>!
Otrzymujesz tę wiadomość, ponieważ Pani Blipotekarka szepnęła nam, że chcesz zostać Czytelnikiem.

Ponieważ udało Ci się prawidłowo wypełnić formularz rejestracyjny, już tylko krok dzieli Cię
od pełnego sukcesu. Podejmij proszę wyzwanie i wejdź na poniższy adres, aby aktywować swoje konto:

<?php echo $this->activationUrl; ?>

Uwaga: powyższy link aktywacyjny jest ważny przez najbliższe 24h.
