<!DOCTYPE html PUBLIC '-//W3C//DTD HTML 4.01 Strict//EN' 'http://www.w3.org/TR/html4/strict.dtd'>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Blipoteka</title>
</head>
<body>
<div style="border: 1px solid #eed">
	<div style="background-color: #FFF8EF; color: #6F4C30; min-height: 64px; padding: 12px 10px; border-bottom: 1px solid #eed">
		<h1 style="font: 24px/1.2 bold 'lucida grande', 'helvetica neue', helvetica, arial, freesans, 'liberation sans', 'numbus sans l', sans-serif; text-shadow: 1px 1px 1px #CFA981; margin: 0; padding: 0; padding-bottom: 8px;"><a style="color: inherit; text-decoration: none"; href="<?php echo $this->serverUrl($this->url(array(), 'index')); ?>">Blipoteka.pl</h1>
		<p style="margin: 0; padding: 0; font: 13px/1.2 'lucida grande', 'helvetica neue', helvetica, arial, freesans, 'liberation sans', 'numbus sans l', sans-serif;">Mię­dzy­mia­stowa biblioteka użyt­kow­ni­ków ser­wisu Blip.pl</p>
	</div>
	<div style="padding: 10px;">
