<h2>Kontakt</h2>

<p>Blipoteka jest wspólnym przedsięwzięciem użytkowników Blipa. Jeśli masz jakieś pytania lub problemy, możesz napisać:</p>
<ul>
<li>na tagu <a rel="nofollow" href="http://blip.pl/tags/blipoteka">#blipoteka</a> na Blipie</li>
<li>do użytkownika <a rel="nofollow" href="http://blipoteka.blip.pl/">^blipoteka</a> (<em>uwaga</em>: konto nie jest monitorowane non-stop)</li>
<li>mailem na <a href="mailto:blipoteka@blipoteka.pl">blipoteka@blipoteka.pl</a></li>
</ul>