<header>
	<h2>Regulamin i polityka prywatności</h2>
</header>
<div class="warning">
<p><strong>Uwaga!</strong> Serwis Blipoteka.pl jest obecnie w fazie intensywnego rozwoju, dlatego też
zastrzegamy sobie możliwość zmiany poniższych zapisów w dowolnej chwili bez uprzedniego powiadomienia
(nawet jeśli zapisy poniżej mówią inaczej).
</p>
<p>W chwili uruchomienia pierwszej wersji stabilnej serwisu, zastrzeżenie, które właśnie czytasz, zostanie usunięte.</p>
</div>
<p>Korzystanie z serwisu Blipoteka.pl oznacza akceptację regulaminu i polityki prywatności:</p>
<h3>Regulamin serwisu</h3>
<ol>
<li>Nigdy nie przekazuj dostępu do kont, dokumentów lub haseł osobom postronnym.</li>
<li>Szanuj książkę, nie niszcz jej, nie ubrudź, nie zalej — niech jak najwięcej osób z niej skorzysta.</li>
<li>Czas przetrzymywania wynosi miesiąc od dnia otrzymania książki do rąk.</li>
<li>Nie przekazuj książki oznaczonej: <q>Wróć</q> innej osobie bez konsultacji z jej właścicielem.</li>
<li>Właściciel książki ma prawo w każdej chwili wycofać książkę z Blipoteki.</li>
<li>Właściciel książki ma prawo wybrać, komu pożycza swoje książki, a komu nie — bez konieczności podawania przyczyn.</li>
<li>Jeśli przetrzymujesz książki, ryzykujesz, że właściciele przestaną Ci je pożyczać. Jeśli nie przestrzegasz regulaminu, ryzykujesz usunięcie z Blipoteki.</li>
<li>Pamiętaj: wszyscy sobie ufamy, jesteśmy z Blipa ;-). Nie nadużywaj tego zaufania, niech idea Blipoteki żyje i działa!</li>
<li>Zastrzegamy sobie możliwość zmian w regulaminie. Informację o zmianach zawsze otrzymasz mailem.</li>
</ol>

<header>
	<h3>Polityka prywatności</h3>
</header>
<ol>
<li>Blipoteka.pl nie gromadzi danych osobowych w rozumieniu ustawy z dnia 29 sierpnia 1997 r. o ochronie danych osobowych (Dz. U. Nr 133, poz. 883 z późn. zm.) oraz ustawy z dnia 18 lipca 2002 r. o świadczeniu usług drogą elektroniczną (Dz. U. Nr 144, poz. 1204).</li>
<li>Dane podane przez Użytkowników, zarówno wymagane przy rejestracji, jak i te podane w trakcie późniejszego użytkownia serwisu, służą jedynie celom osobistym, tj. pożyczaniu sobie nawzajem książek.</li>
<li>Dane osobowe wymagane do korzystania z serwisu (adres e-mail i nick z serwisu Blip.pl, miejscowość zamieszkana) ani żadne inne dane nie będą udostępniane innym podmiotom.</li>
<li>Wszystkie pozostałe dane (płeć, imię i nazwisko) są nieobowiązkowe. Użytkownik podaje je dobrowolnie i na własną odpowiedzialność. Blipoteka.pl nie będzie tych danych przetwarzać w celach innych niż funkcjonowanie serwisu ani udostępniać innym podmiotom.</li>
<li>O wszelkich ewentualnych zmianach w Polityce Prywatności Użytkownicy będą poinformowani e-mailowo.</li>
</ol>
