<?php
$this->headTitle()->append($this->species->name);
$this->headTitle()->append('Melody '.$this->melodyA->id.' vs '.$this->melodyB->id);
?>
<script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script>
<h2>Hover your mouse over the track to hear it<br />Compare and pick the best one</h2>

<div id="jquery_jplayer_1" class="jp-jplayer"></div>
<div id="jquery_jplayer_2" class="jp-jplayer"></div>

<div id="dialog-overlay"></div>
<div id="dialog-box">
    <div class="dialog-content">
        <div id="dialog-message"></div>
    </div>
</div>

<div id="bar">
	 <div id="first" class="element track1">
        
		<div class="bottom oneheight">
			<div class="infobox">
        		<div class="facebooklike">
            	<fb:like href="http://nandu.amplifuge.com<?php echo $this->url(array('speciesId' => $this->species->id, 'a' => $this->melodyA->id), 'open', true); ?>" layout="button_count" show_faces="true" width="50" font="segoe ui"></fb:like>
        		</div>
				<h3>
    			Genotype one (<?php echo $this->melodyA->id?>)
                </h3>
				<pre style="display: none;"><?php echo $this->melodyA->getAudioFilename()?></pre>
			</div>
		</div>
		<div class="progressbar oneheight">
		</div>
		<div class="right oneheight">
		</div>
		<div class="notes oneheight">
		<?php
		foreach ($this->melodyA->getNotesAsArray() as $key => $value)
		{
		    $marginLeft = ($key)*17;
		    $marginTop = 60-($value*2);
			echo '<div class="note notetrack1" style="margin-left:'.$marginLeft.'px;margin-top:'.$marginTop.'px;"></div>';
		}
		?>
		</div>
		<a href="<?php echo $this->url(array('speciesId' => $this->species->id, 'a' => $this->melodyA->id, 'b' => $this->melodyB->id), 'vote', true); ?>" class="track1 oneheight"></a>
	</div>
	<div id="second" class="element track2">
		<div class="bottom oneheight">
			<div class="infobox">
        		<div class="facebooklike">
        		<fb:like href="http://nandu.amplifuge.com/melody/<?php echo $this->melodyB->id?>/from/<?php echo $this->species->id?>/" layout="button_count" show_faces="true" width="50" font="segoe ui"></fb:like>
        		</div>
				<h3>Genotype two (<?php echo $this->melodyB->id?>)</h3>
				<pre style="display: none;"><?php echo $this->melodyB->getAudioFilename()?></pre>
			</div>
		</div>
		<div class="progressbar oneheight">
		</div>
		<div class="right oneheight">
		</div>
		<div class="notes oneheight">
		<?php
		foreach ($this->melodyB->getNotesAsArray() as $key => $value)
		{
		    $marginLeft = ($key)*17;
		    $marginTop = 60-($value*2);
			echo '<div class="note notetrack2" style="margin-left:'.$marginLeft.'px;margin-top:'.$marginTop.'px;"></div>';
		}
		?>
		</div>
		<a href="<?php echo $this->url(array('speciesId' => $this->species->id, 'b' => $this->melodyA->id, 'a' => $this->melodyB->id), 'vote', true); ?>" class="track2 oneheight"></a>
	</div>
</div>
<div class="debuginfo break">
<p>
<?php
/*
foreach($genotypes as $id => $genotype)
{
    echo "<h3>Debug data for genotype nr $id: </h3><p>";
    foreach($genotype as $note)
    {
        $degreeInfo = $music->getDegreeWithOctaveFromNote($note, MusicScales::Major(), NoteSearchMode::UP);
        echo $music->getHumanReadableNoteFromDegree($degreeInfo, 'American').', ';
    }
    echo '</p>';
}
if (defined('DEBUG'))
{
    echo '<div class="debuglog"><pre>';
    echo nl2br(file_get_contents(DEBUG.'/log.txt'), true);
    echo '</pre></div>';
    unlink(DEBUG.'/log.txt');
}
$mainTimer->stop();
echo '<p>Page generation time: '.$mainTimer->get().'</p>';
*/
?>
</p>
</div>

<script type="text/javascript">
//<![CDATA[

//Popup dialog
function popup(message) {
         
    // get the screen height and width  
    var maskHeight = $(document).height();  
    var maskWidth = $(window).width();
     
    // calculate the values for center alignment
    var dialogTop =  (maskHeight/3) - ($('#dialog-box').height());  
    var dialogLeft = (maskWidth/2) - ($('#dialog-box').width()/2); 
     
    // assign values to the overlay and dialog box
    $('#dialog-overlay').css({height:maskHeight, width:maskWidth}).show();
    $('#dialog-box').css({top:dialogTop, left:dialogLeft}).show();
     
    // display the message
    $('#dialog-message').html(message);
             
}

$(document).ready(function(){
    // this is quite dirty and should be moved to a separate file //
<?php
$files = array();
// this was: $this->melodyB->getAudioFilename() but $this->melodyX is not available in the main layout for the top bar
$files[] = $this->baseUrl('/audio/'.$this->melodyAfilename);
$files[] = $this->baseUrl('/audio/'.$this->melodyBfilename);
for ($id = 1; $id <= 2; $id++)
{
    $file = $files[$id-1];
    echo <<< "EOT"
        window.setTimeout(jplayerSetup$id, 800); //FIX ME, this is a poor's man synchronization for the asynchronous generation :-D
        function jplayerSetup$id()
        {
            $("#jquery_jplayer_$id").jPlayer({
            ready: function () {
                $(this).jPlayer("setMedia", {
                    oga: "$file.ogg",
                    mp3: "$file.mp3"
        		});
        	},
        	ended: function (event) {
        		//$(this).jPlayer("play");
        	},
        	swfPath: "js",
        	supplied: "oga, mp3",
        	cssSelectorAncestor: "",
        	cssSelector: {
        	  play: "",
        	  pause: "",
        	  stop: "",
        	  videoPlay: "",
        	  seekBar: "",
        	  playBar: "",
        	  mute: "#mute",
        	  unmute: "#unmute",
        	  volumeBar: "",
        	  volumeBarValue: "",
        	  currentTime: "#currentTime",
        	  duration: ""
              }
            })
            .bind($.jPlayer.event.play, function() { // Using a jPlayer event to avoid both jPlayers playing together.
            		$(this).jPlayer("pauseOthers");
            });
        }

EOT;
}
?>
    window.setTimeout(showGenotypes, 1000); //generation of one genotype to mp3 and ogg takes about 500ms, so 1 second is plenty

    popup('<p>Please wait while the genotypes are being evolved</p>');
    $("body").css({ cursor:"wait" });
    function showGenotypes()
    {
        $('#dialog-overlay, #dialog-box').hide(); 
        $("body").css({ cursor:"auto" });
        $("#bar").fadeIn(500);
    }
    
    // if user resize the window, call the same function again
    // to make sure the overlay fills the screen and dialogbox aligned to center    
    $(window).resize(function () {
        //only do it if the dialog box is not hidden
        if (!$('#dialog-box').is(':hidden')) popup();       
    }); 
    
    
    $("div.track1").mouseenter( function() {
      $("#jquery_jplayer_1").jPlayer("play");
    }).mouseleave(function(){
      $("#jquery_jplayer_1").jPlayer("stop");
    });
    
    $("div.track2").mouseenter( function() {
      $("#jquery_jplayer_2").jPlayer("play");
    }).mouseleave(function(){
      $("#jquery_jplayer_2").jPlayer("stop");
    });
    
});

//]]>
</script>