<?php
$this->headTitle()->append($this->species->name);
$this->headTitle()->append('Melody '.$this->melodyA->id.' vs '.$this->melodyB->id);
?>
<!--<script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script>-->
<h2>Hover your mouse over each genotype to hear them.<br />Compare and pick the best one by clicking on it.</h2>

<div id="jquery_jplayer_1" class="jp-jplayer"></div>
<div id="jquery_jplayer_2" class="jp-jplayer"></div>


<div id="bar">
	 <div id="first" class="element track1">
        
		<div class="bottom oneheight">
			<div class="infobox">
        		<div class="facebooklike">
            	<fb:like href="http://apps.facebook.com/nandumusic<?php echo $this->url(array('speciesId' => $this->species->id, 'a' => $this->melodyA->id), 'open', true); ?>" layout="button_count" show_faces="true" width="50" font="segoe ui"></fb:like>
        		</div>
				<h3>
    			Genotype A (ID: <?php echo $this->melodyA->id?>)
                </h3>
				<pre style="display: none;"><?php echo $this->melodyA->getAudioFilename()?></pre>
			</div>
		</div>
		<div class="progressbar oneheight">
		</div>
		<div class="right oneheight">
		</div>
		<div class="notes oneheight">
		<?php
		foreach ($this->melodyA->getNotesAsArray() as $key => $value)
		{
		    $marginLeft = ($key)*17;
		    $marginTop = 60-($value*2);
			echo '<div class="note notetrack1" style="margin-left:'.$marginLeft.'px;margin-top:'.$marginTop.'px;"></div>';
		}
		?>
		</div>
		<a href="<?php echo $this->url(array('speciesId' => $this->species->id, 'a' => $this->melodyA->id, 'b' => $this->melodyB->id), 'vote', true); ?>" class="track1 oneheight"></a>
	</div>
	<div id="second" class="element track2">
		<div class="bottom oneheight">
			<div class="infobox">
        		<div class="facebooklike">
        		<fb:like href="http://apps.facebook.com/nandumusic<?php echo $this->url(array('speciesId' => $this->species->id, 'a' => $this->melodyB->id), 'open', true); ?>/" layout="button_count" show_faces="true" width="50" font="segoe ui"></fb:like>
        		</div>
				<h3>Genotype B (ID: <?php echo $this->melodyB->id?>)</h3>
				<pre style="display: none;"><?php echo $this->melodyB->getAudioFilename()?></pre>
			</div>
		</div>
		<div class="progressbar oneheight">
		</div>
		<div class="right oneheight">
		</div>
		<div class="notes oneheight">
		<?php
		foreach ($this->melodyB->getNotesAsArray() as $key => $value)
		{
		    $marginLeft = ($key)*17;
		    $marginTop = 60-($value*2);
			echo '<div class="note notetrack2" style="margin-left:'.$marginLeft.'px;margin-top:'.$marginTop.'px;"></div>';
		}
		?>
		</div>
		<a href="<?php echo $this->url(array('speciesId' => $this->species->id, 'b' => $this->melodyA->id, 'a' => $this->melodyB->id), 'vote', true); ?>" class="track2 oneheight"></a>
	</div>
</div>
<div class="debuginfo break">
<h1>How to use?</h1>
<p>
When you are in the <i>evolve</i> mode you are faced with two blobs of genetic material. 
<br/> Hover your mouse over the blobs to hear them. <br/>Pick one that you like best by clicking on it. </p>
<p>
The one you have chosen will become a parent for a new generation and will also survive to the next one in an unchanged form as 'Genotype A' (the one on the left).</p>
<p>This way, you can keep clicking on Genotype A until the other one sounds better to you. You may stop this process at any time.</p>
<p>Visual representation may help you notice the evolutionary process. </p>
<h1>Look-alike?</h1>
<p>Like in real life, it sometimes happens that two members of species look very similar - or in this case identical.</p>
<p>If that happens you simply have to click on either one in order to continue the evolution. Enough melody-organisms are being generated, breed or mutated, so that the whole genetic pool will not be influenced by one pair of look-alikes.</p>
<h1>MIDI</h1>
<p>You can download the MIDI files for each Genotype <a href="#toppanel" class="openPanel">from the slide menu</a> (click to open).</p>
<?php
/*
foreach($genotypes as $id => $genotype)
{
    echo "<h3>Debug data for genotype nr $id: </h3><p>";
    foreach($genotype as $note)
    {
        $degreeInfo = $music->getDegreeWithOctaveFromNote($note, MusicScales::Major(), NoteSearchMode::UP);
        echo $music->getHumanReadableNoteFromDegree($degreeInfo, 'American').', ';
    }
    echo '</p>';
}
if (defined('DEBUG'))
{
    echo '<div class="debuglog"><pre>';
    echo nl2br(file_get_contents(DEBUG.'/log.txt'), true);
    echo '</pre></div>';
    unlink(DEBUG.'/log.txt');
}
$mainTimer->stop();
echo '<p>Page generation time: '.$mainTimer->get().'</p>';
*/
?>
</div>

<script type="text/javascript">
//<![CDATA[


$(document).ready(function(){
    // this is quite dirty and should be moved to a separate file //
<?php
$files = array();
// this was: $this->melodyB->getAudioFilename() but $this->melodyX is not available in the main layout for the top bar
$files[] = $this->baseUrl('/audio/'.$this->melodyAfilename);
$files[] = $this->baseUrl('/audio/'.$this->melodyBfilename);
for ($id = 1; $id <= 2; $id++)
{
    $file = $files[$id-1];
    echo <<< "EOT"
        window.setTimeout(jplayerSetup$id, 800); //FIX ME, this is a poor's man synchronization for the asynchronous generation :-D
        function jplayerSetup$id()
        {
            $("#jquery_jplayer_$id").jPlayer({
            ready: function () {
                $(this).jPlayer("setMedia", {
                    oga: "$file.ogg",
                    mp3: "$file.mp3"
        		});
        	},
        	ended: function (event) {
        		//$(this).jPlayer("play");
        	},
        	swfPath: "js",
        	supplied: "oga, mp3",
        	cssSelectorAncestor: "",
        	cssSelector: {
        	  play: "",
        	  pause: "",
        	  stop: "",
        	  videoPlay: "",
        	  seekBar: "",
        	  playBar: "",
        	  mute: "#mute",
        	  unmute: "#unmute",
        	  volumeBar: "",
        	  volumeBarValue: "",
        	  currentTime: "#currentTime",
        	  duration: ""
              }
            })
            .bind($.jPlayer.event.play, function() { // Using a jPlayer event to avoid both jPlayers playing together.
            		$(this).jPlayer("pauseOthers");
            });
        }

EOT;
}
?>
    window.setTimeout(showGenotypes, 1000); //generation of one genotype to mp3 and ogg takes about 500ms, so 1 second is plenty
    
    var pleaseWaitNote = '<p>Please wait while the genotypes are being evolved</p>';
    popup(pleaseWaitNote);
    $("body").css({ cursor:"wait" });
    function showGenotypes()
    {
        $('#dialog-overlay, #dialog-box').hide(); 
        $("body").css({ cursor:"auto" });
        $("#bar").fadeIn(500);
    }
    
    // if user resize the window, call the same function again
    // to make sure the overlay fills the screen and dialogbox aligned to center    
    $(window).resize(function () {
        //only do it if the dialog box is not hidden
        if (!$('#dialog-box').is(':hidden')) popup();       
    }); 
    
    
    
    $("div.track1").mouseenter( function() {
      $("#jquery_jplayer_1").jPlayer("play");
    }).mouseleave(function(){
      $("#jquery_jplayer_1").jPlayer("stop");
    }).click(function(){ popup(pleaseWaitNote); $("body").css({ cursor:"wait" }); });
    
    $("div.track2").mouseenter( function() {
      $("#jquery_jplayer_2").jPlayer("play");
    }).mouseleave(function(){
      $("#jquery_jplayer_2").jPlayer("stop");
    }).click(function(){ popup(pleaseWaitNote); $("body").css({ cursor:"wait" }); });
    
});

//]]>
</script>