<link href="http://cdn.jotfor.ms/jotform.cssgz?3.1.100" rel="stylesheet" type="text/css" />
<style type="text/css">
    .form-label{
        width:150px !important;
    }
    .form-label-left{
        width:150px !important;
    }
    .form-line{
        padding:10px;
    }
    .form-label-right{
        width:150px !important;
    }
    body, html{
        margin:0;
        padding:0;
        background:false;
    }

    .form-all{
        margin:0px auto;
        padding-top:0px;
        width:650px;
        color:Black !important;
        font-family:Verdana;
        font-size:12px;
    }
</style>

<script src="http://cdn.jotfor.ms/jotform.jgz?3.1.100" type="text/javascript"></script>
<script type="text/javascript">
   JotForm.init(function(){
      $('input_4').hint(' my species');
      $('input_6').slider({ width: '200', maxValue: '250', value: '97'});
      $('input_8').spinner({ imgPath:'http://www.jotform.com/images/', width: '60', maxValue:'', minValue:'20', allowNegative: false, addAmount: 1, value:'60' });
      JotForm.description('input_8', 'This is the reference note of your scale - 60 is the Middle C, 62 Middle D and so on...<br />Therefore selecting 60 will mean that your species will mutate with a high probability of being in C scale (if you selected Major, C Major)');
   });
</script>

<form class="jotform-form" action="#" method="post" name="form_10352946635" id="10352946635" accept-charset="utf-8">
    <input type="hidden" name="formID" value="10352946635" />
    <div class="form-all">
        <ul class="form-section">
            <li id="cid_1" class="form-input-wide">
                <div class="form-header-group">
                    <h2 id="header_1" class="form-header">
                        Creating new species
                    </h2>
                </div>

            </li>
            <li class="form-line" id="id_4">
                <label class="form-label-left" id="label_4" for="input_4">
                    Name of species<span class="form-required">*</span>
                </label>
                <div id="cid_4" class="form-input">
                    <input type="text" class="form-textbox validate[required]" id="input_4" name="q4_nameOf" size="20" />
                </div>

            </li>
            <li class="form-line" id="id_3">
                <label class="form-label-left" id="label_3" for="input_3">
                    Scale<span class="form-required">*</span>
                </label>
                <div id="cid_3" class="form-input">
                    <select class="form-dropdown validate[required]" style="width:150px" id="input_3" name="q3_scale">
                        <option>  </option>

                        <option selected="selected" value="Major (dur)"> Major (dur) </option>
                        <option value="Minor natural (moll)"> Minor natural (moll) </option>
                        <option value="Minor harmonic"> Minor harmonic </option>
                    </select>
                </div>
            </li>

            <li class="form-line" id="id_6">
                <label class="form-label-left" id="label_6" for="input_6">
                    Tempo BPM<span class="form-required">*</span>
                </label>
                <div id="cid_6" class="form-input">
                    <input type="range" class="form-textbox validate[required]" id="input_6" name="q6_tempoBpm" />
                </div>
            </li>

            <li class="form-line" id="id_7">
                <label class="form-label-left" id="label_7" for="input_7">
                    Instrument<span class="form-required">*</span>
                </label>
                <div id="cid_7" class="form-input">
                    <select class="form-dropdown validate[required]" style="width:180px" id="input_7" name="q7_instrument">
                        <option>  </option>

                        <option value="Piano"> Piano </option>
                        <option selected="selected" value="Vibes"> Vibes </option>
                        <option value="Organ"> Organ </option>
                    </select>
                </div>
            </li>

            <li class="form-line" id="id_8">
                <label class="form-label-left" id="label_8" for="input_8">
                    Reference note<span class="form-required">*</span>
                </label>
                <div id="cid_8" class="form-input">
                    <input type="number" id="input_8" name="q8_referenceNote" />
                </div>
            </li>

            <li class="form-line" id="id_2">
                <div id="cid_2" class="form-input-wide">
                    <div style="margin-left:156px" class="form-buttons-wrapper">
                        <button id="input_2" type="submit" class="form-submit-button">
                            Create!
                        </button>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</form>


<form method="post">
	<input type="submit" name="create" value="Create new species!">
</form>