<footer id="footer">
	<div class="container_12">
		<ul class="grid_4">
			<li><a href="<?php echo $this->url(array(), 'index'); ?>">Home</a></li>
			<li><a href="<?php echo $this->url(array(), 'blog'); ?>">Developement Blog</a></li>
			<li><a href="<?php echo $this->url(array(), 'contact'); ?>">Contact</a></li>
		</ul>
		<p class="grid_8">Copyright &copy; 2011 <a href="<?php echo $this->url(array(), 'contact'); ?>">Bazyli Brzóska & Michał Buczek</a>. MIT licensed source code <a href="http://github.com/niieani/nandu">downloadable</a> from GitHub.</p>
	</div>
</footer>
