<footer id="footer">
	<div class="container_12">
		<!--<ul class="grid_4">
            <li><a href="<?php echo $this->url(array(), 'index'); ?>">Home</a></li>
			<li><a href="<?php echo $this->url(array(), 'blog'); ?>">Developement Blog</a></li>
			<li><a href="<?php echo $this->url(array(), 'contact'); ?>">Contact</a></li>
		</ul>-->
        <p><strong>ñandú</strong> is MIT licensed</p>
        <p>Source code <a href="http://github.com/niieani/nandu">downloadable</a> from GitHub</p>
		<p>Copyright &copy; 2011 <a href="mailto:nandu@amplifuge.com">Bazyli Brzóska & Michał Buczek</a></p>
	</div>
</footer>
