<footer id="footer">
	<div class="container_12">
		<ul class="grid_4">
			<li><a href="<?php echo $this->url(array(), 'index'); ?>">Strona główna</a></li>
			<li><a href="<?php echo $this->url(array(), 'terms'); ?>">Regulamin</a></li>
			<li><a href="<?php echo $this->url(array(), 'blog'); ?>">Blog</a></li>
			<li><a href="<?php echo $this->url(array(), 'contact'); ?>">Kontakt</a></li>
		</ul>
		<p class="grid_8">Copyright &copy; 2010-2011 <a href="<?php echo $this->url(array(), 'contact'); ?>">Blipoteka Team</a>. Kod źródłowy na licencji BSD <a href="http://github.com/argasek/blipoteka">do pobrania</a> na GitHub.</p>
	</div>
</footer>
