<div style="width: 956px; height: 384px; border: 1px solid #ccc; padding: 1px; position: absolute; top: 50%; left: 50%; margin-left: -492px; margin-top: -194px">
	<div style="width: 512px; height: 384px; float: left;">
		<img style="display: block;" src="<?php echo $this->baseUrl('img/404.jpeg'); ?>" alt="404 page not found">
	</div>
	<div style="width: 428px; padding-left: 14px; padding-top: 32px; height: 334px; float: left; overflow: hidden">
		<h1 style="font: bolder 48px/1.1 Arial, Helvetica, sans-serif; color: #866; margin: 0.5em auto;">403 Brak dostępu</h1>
		<p style="font: normal 14px/1.2 Arial, Helvetica, sans-serif; margin: 0.5em auto;">Strona, do której próbowano uzyskać dostęp, wymaga <a href="#">zalogowania</a>.</p>
		<p style="font: normal 14px/1.2 Arial, Helvetica, sans-serif; margin: 0.5em auto;">Nie masz jeszcze konta w Blipotece? <a href="#">Zarejestruj się</a>, zajmie Ci to nie dłużej niż minutę!</p>
		<p style="font: normal 14px/1.2 Arial, Helvetica, sans-serif; margin: 0.5em auto;">Jesteś zalogowany(-a), ale widzisz ten komunikat? <a href="#">Napisz do nas!</a></p>
		<p style="font: normal 14px/1.2 Arial, Helvetica, sans-serif; margin: 0.5em auto;"><span style="font-weight: bolder;">Blipoteka.pl</span> • Twoja internetowa biblioteka</p>
	</div>
</div>
